### ISSUE TITLE
Module - Clarification

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/terraform-gitops-cp4ba-iaf-operator#2]
How is module different than gitops-cp-cp4ba-operator ? Whats purpose of this module ?

@triceam @dineshchandrapandey - FYI

**Comment by triceam** [comment]
@balasgit @dineshchandrapandey 

I renamed the CP4BA repos, updated their metadata, and added the latest (shared) github workflows:

- IBM Automation Foundation Operator is now https://github.com/cloud-native-toolkit/terraform-gitops-cp4ba-iaf-operator
- IBM Cloud Pak for Business Automation Operator is now https://github.com/cloud-native-toolkit/terraform-gitops-cp4ba-operator
- Business Automation navigator is now https://github.com/cloud-native-toolkit/terraform-gitops-cp4ba-ban

I updated all of the metadata, including IDs, so you will need to update your dependencies and references.  However, I did run into a problem.  I had to force merge my changes, skipping the tests b/c all of the test cases were failing for me.  I noticed on all the repos there look to be active development branches.  You will need to pull the latest from `main` into your dev branches.  Can you also help get the test cases passing?   (I am not familiar with CP4BA functionality, so I’m not sure what is needed, or if the tests on the main branch are up to date.)
The module catalog is rebuilding now, so they should be updated on https://modules.cloudnativetoolkit.dev/ shortly.

**Comment by triceam** [comment]
Now showing up in the catalog
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/974294/161631195-140a5887-dc9a-47ca-8190-96099a0485ea.png">
